# -*- coding: utf-8 -*-
"""groupby funcation using pandas .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prrnrrwF2QTbNzAMUYBl5fnNj1MF3uju
"""

import numpy as np
import pandas as pd

# create DataFrame using list

Student1 = [[100,90,70],
            [90,60,7],
            [120,100,14],
            [80,50,2]]

df1 = pd.DataFrame(Student1,columns=["iQ","mrks","package"])
df1

dic1 = {
    "id":[100,90,120,70],
    "marks":[79,89,67,45],
    "package":[70,12,65,8]
}

df2 = pd.DataFrame(dic1)
df2

df3 = pd.read_csv("/content/Virat Kohli Century.csv")

df3.head()

df3.tail()

df3.shape

df3.dtypes

print(type(df3))
print()
print(dir(df3))

df3.index

df3.columns

df3.values # store data in 2D dimension numpy array

df3.sample(5)

df3.info()

df3.isnull().sum()

df3.describe()

df3[df3.duplicated()]

df3.duplicated().sum()

df2

df2.rename(columns={"marks":"percentage","package":"LPA"},inplace=True)

df2

df2.sum()

df2.sum(axis=1) #  row wise sum

df2.sum(axis=0) # columns wise sum

df2.var()

df2.var(axis=1)

df2.var(axis=0) # by defult

df3.head()

df3.columns

print(df3[['Inning','Score', 'Year']])
print(type(df3[['Inning','Score', 'Year']]))

print(df3['Host Nation'])
print(type(df3['Host Nation']))

df3.head()

df3.columns

df4 = df3["Host Nation"]=="India"
df_4 = df3[df4]
df_4[["Score","Against","Format","Win"]].set_index("Score")

df4 = df3[df3["Host Nation"]=="India"]
df4[["Score","Venue","Against",'Format']].sort_values("Score").head(5).set_index("Venue")

df3.columns

df5 = df3[(df3["Win"]=="Yes")|(df3["Win"]=="No")]
df5[['Score','Win','Against']]

df5 = df3[(df3["Win"]=="Yes")|(df3["Win"]=="No")]
df5[['Score','Win','Against']]
df5[df5['Win']=="No"][["Score","Win",'Against']]

df3["Host Nation"].value_counts()

df3[(df3["Host Nation"] == "Australia") & (df3["Win"] == "Yes")][["Score","Against","Year","Venue"]].set_index("Year")

df3[(df3["Host Nation"] == "Australia") & (df3["Win"] == "No")][["Score","Against","Year","Venue"]].set_index("Year")

df3[(df3["Host Nation"] == "India") & (df3["Win"] == "No")][["Score","Against","Year","Venue"]].set_index("Year")

df3[(df3["Host Nation"] == "India") & (df3["Win"] == "Yes")][["Score","Against","Year","Venue"]].set_index("Year")

df3[(df3["Host Nation"] == "India") & (df3["Win"] == "Yes")][["Score","Against","Year","Venue"]].set_index("Year").shape

df3[(df3["Host Nation"] == "India") & (df3["Win"] == "Yes")][["Score","Against","Year","Venue"]].set_index("Year").shape[0]

df3.info()

df3["Number"] = df3["Number"].astype("int32")
df3.info()

df3[["Number","Balls","Wickets lost"]]= df3[["Number","Balls","Wickets lost"]].astype("int32")
df3.info()

df3["Strike Rate"] = df3["Strike Rate"].astype("float32")
df3.info()

df6 = pd.read_csv("/content/ipl-matches.csv")
df6.head()

df6[df6["MatchNumber"].str.isdigit()].head()

df6.columns

df6[~df6["MatchNumber"].str.isdigit()]['Player_of_Match'].sample(5)

df6[~df6["MatchNumber"].str.isdigit()]['Player_of_Match'].value_counts()

df6[~df6["MatchNumber"].str.isdigit()][['Player_of_Match','MatchNumber']].value_counts().astype("int32")

df6[~df6["MatchNumber"].str.isdigit()][['Player_of_Match','MatchNumber']].value_counts().astype("int32").rename("Number_of_Player_of_Match")

df6[~df6["MatchNumber"].str.isdigit()][['Player_of_Match','MatchNumber']].value_counts().astype("int32").rename("Number_of_Player_of_Match").reset_index()

df6.columns

df6[~df6["MatchNumber"].str.isdigit()][['Player_of_Match','MatchNumber']].value_counts().astype("int32").rename("Number_of_Player_of_Match").reset_index().rename(columns={'MatchNumber':"matchname"})

df6.columns

df6["Team1"].value_counts()

df6["Team2"].value_counts()

df6["Team1"].value_counts() + df6["Team2"].value_counts()

(df6["Team1"].value_counts() + df6["Team2"].value_counts()).sort_values(ascending=False)

(df6["Team1"].value_counts() + df6["Team2"].value_counts()).sort_values(ascending=False).rename("playedMatch")

#

df6.sort_values(["Team1"])

df6.sort_values(["Team1"],ascending=False)

df6.columns

df6.sort_values(["Season","Team2"])

df6.sort_values(["Season","Team2"],ascending=[True,False])

df6.isnull().sum()

df6.sort_values("City")

df6.sort_values("City",na_position="first")

df6.sort_values("City",na_position="first",ascending=False)

df6["Venue"].unique()

#find the last match played by virat kohli in Delhi

df6.columns

df6.head()

df6['all_players'] = df6['Team1Players'] + df6['Team2Players']
df6.head()

def did_kohli_play(players_list):
  return 'V Kohli' in players_list

df6['did_kohli_play'] = df6['all_players'].apply(did_kohli_play)
df6.columns

df6.head()

df6.columns

df6[(df6['City'] == 'Delhi') & (df6['did_kohli_play'] == True)]

df6[(df6['City'] == 'Delhi') & (df6['did_kohli_play'] == True)].drop_duplicates(subset=['City','did_kohli_play'],keep='first')

movie = pd.read_csv("/content/imdb-top-1000 (2).csv")
movie.head(1)

genres = movie.groupby("Genre")

genres.sum()

# find the top 3 genres by total earning
movie.groupby("Genre").sum()["Gross"].sort_values(ascending=False)

movie.groupby("Genre").sum()["Gross"].sort_values(ascending=False).head(3)

# second ways

movie.groupby("Genre")["Gross"].sum().sort_values(ascending=False).head(3)

movie.columns

#find the genre with highest avg IMDB rating
movie.groupby("Genre")['IMDB_Rating'].mean().sort_values(ascending=False)

movie.groupby("Genre")['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

movie.columns

# find director with most popularity
movie.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False)

movie.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

movie.columns

# find the highest rated movie of each genre
result = movie.loc[movie.groupby('Genre')["IMDB_Rating"].idxmax()]

result

result = movie.sort_values("IMDB_Rating", ascending=False).drop_duplicates("Genre")
result

movie.columns

#find number of movies done by each actor

movie.groupby('Star1')['Star1'].count()

movie.groupby('Star1')['Star1'].count().sort_values(ascending=False)

# find total number of groups -- len
len(movie.groupby("Genre"))

movie["Genre"].nunique()

# find items in each group -- size
movie.groupby("Genre").size()

# second ways
movie["Genre"].value_counts().rename("no_of_movie")

## first()/last() / nth item\ base find out first,last,and nth movie in Genre

genres = movie.groupby("Genre")
genres.first()

genres.last()

genres.nth(6)

genres.nth(0)

genres.nth(10)

# get_group / vs filtering
genres.get_group("Horror")   # find out all horror movie in this Genre

genres.get_group("Mystery")   # find out all Mystery movie in this Genre

genres.get_group("Fantasy")

# second method using

movie[movie["Genre"]=="Fantasy"]

movie[movie["Genre"]=="Mystery"]

movie[movie["Genre"]=="Family"]

genres.groups

genres.describe()

genres.sample()

genres.nunique()

genres.sample(2,replace=True)

genres.sample(3,replace=True)

genres.agg(["min","max"])

movie.columns

genres.agg({
               "Runtime":"mean",
               "IMDB_Rating":"mean",
               'No_of_Votes':"sum",
               'Gross':"sum",
              'Metascore':"sum"
})

genres.agg({
               "Runtime":["mean","min","max"],
               "IMDB_Rating":"mean",
               'No_of_Votes':["sum","max"],
               'Gross':"sum",
              'Metascore':"sum"
})

# using loop on group

for group,data in genres:
    print(data)

genres

#find number of movies starting with A for each group

def start_with_A(group):
    print(group)
    return group

genres.apply(start_with_A)

def start_with_A(group):
    print(type(group))
    return group

genres.apply(start_with_A)

def start_with_A(group):
    return group["Series_Title"].str.startswith("A")

genres.apply(start_with_A)

def start_with_A(group):
    return group["Series_Title"].str.startswith("A").sum()

genres.apply(start_with_A)

def start_with_A(group):
    return group["Series_Title"].str.endswith("A").sum()

genres.apply(start_with_A)

#find ranking of each movie in the group according to IMDB score

movie.columns

movie["Rank_in_Genre"] = movie.groupby("Genre")["IMDB_Rating"].rank(ascending=False)
print(movie[["Series_Title","Genre","IMDB_Rating","Rank_in_Genre"]])

def Rank_in(group):
    group["Rank_in"] = group["IMDB_Rating"].rank(ascending=False)
    return group

genres.apply(Rank_in)

#find normalized IMDB rating group wise

def Normalized_Rating(group):
    group["Normalized_Rating"] = group["IMDB_Rating"]-group["IMDB_Rating"].mean()/(group["IMDB_Rating"].max()-group["IMDB_Rating"].min())
    return group

genres.apply(Normalized_Rating)

# groupby on multiple cols
movie.columns

due = movie.groupby(['Director','Star1'])
due.size()

due.get_group(("Zaza Urushadze","Lembit Ulfsak"))

due.get_group(("Aamir Khan","Amole Gupte"))

# find the most earning actor -- director combo

due["Gross"].sum()

due["Gross"].sum().sort_values(ascending=False).head(1)

## find the best(in-terms of metascore(avg)) actor -- genre combo
movie.columns

movie.groupby(['Star1', 'Genre'])["Metascore"].mean().reset_index().sort_values("Metascore",ascending=False).head(1)

# agg on multiple groupby
movie.columns

due = movie.groupby(['Director','Star1'])
due[["IMDB_Rating","No_of_Votes","Gross","Metascore"]].agg(["mean","max","min"])

movie.select_dtypes(include="number").agg(["mean","max","min"])

movie.groupby(["Director","Star1"])[["IMDB_Rating","Gross","No_of_Votes"]].agg(["mean","max","min"])

movie.groupby(["Director","Star1",'Genre'])[["IMDB_Rating","Gross","No_of_Votes"]].agg(["mean","max","min"])

dT = pd.read_csv("/content/deliveries (2).csv")
dT.head()

dT.columns

#find the top 10 batsman in terms of runs

dT.groupby("batsman")["batsman_runs"].sum()

dt = dT.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).head(10)
dt

# find the batsman with max no of sixes
six = dT[dT['batsman_runs']==6]
six.groupby("batsman")["batsman"].count().sort_values(ascending=False)

six.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(1)

six.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(1).index[0]

# find batsman with most number of 4's and 6's in last 5 overs

last_5over = dT[dT["over"]>15]
last_5over = last_5over[(last_5over["batsman_runs"]==4) | (last_5over["batsman_runs"]==6)]
last_5over.groupby("batsman")["batsman"].count()
last_5over.groupby("batsman")["batsman"].count().sort_values(ascending=False)
last_5over.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(1)

last_5over.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(1).index[0]

#find V Kohli's record against all teams
tem_df = dT[dT["batsman"]=="V Kohli"]
tem_df.groupby("bowling_team")["batsman_runs"].count().reset_index()

#find MS Dhoni's record against all teams
tem_df = dT[dT["batsman"]=="MS Dhoni"]
tem_df.groupby("bowling_team")["batsman_runs"].count().rename("batsman_run").reset_index()

# Create a function that can return the highest score of any batsman
dT.columns

tem1 = dT[dT['batsman']=="V Kohli"]
tem1.groupby('match_id')["batsman_runs"].sum().sort_values(ascending=False).head(1)

dT["batsman"].unique()

def highest_score(batsman):
    tem1 = dT[dT['batsman']== batsman]
    return tem1.groupby('match_id')["batsman_runs"].sum().sort_values(ascending=False).head(1)

highest_score("AD Russell")