# -*- coding: utf-8 -*-
"""Merging, Joining & Concatenating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZObra5hKVo6oXjYPPWzgx2lu02b0scpe
"""

import pandas as pd
import numpy as np

nov = pd.read_csv("/content/reg-month1.csv")
dec = pd.read_csv("/content/reg-month2.csv")

nov.shape

dec.shape

pd.concat([nov,dec])

pd.concat([nov,dec]).shape

reg = pd.concat([nov,dec],ignore_index=True)
reg

multi = pd.concat([nov,dec],keys=["nov","dec"])
# multiindex DataFrame
multi

multi.loc["nov"]

multi.loc["dec"]

multi.loc[("dec",0)]

multi.loc[("nov",5)]

df = pd.concat([nov,dec],axis =1)
df

df = pd.concat([nov,dec],axis =1)
df.iloc[1:19,0:3]

pd.concat([nov,dec],axis =0)

pd.concat([nov,dec],axis =0,ignore_index=True)

student = pd.read_csv("/content/students.csv")
student

reg.head()

student.head()

# inner join
student.merge(reg,how="inner",on= "student_id")

# left join
student.merge(reg,how="left",on= "student_id")

# right join
student.merge(reg,how="right",on= "student_id")

# outer join
student.merge(reg,how="outer",on= "student_id")

course = pd.read_csv("/content/courses.csv")
course

reg

# inner join

course.merge(reg).shape

course.merge(reg,how = "inner",on = "course_id")

course.merge(reg,how = "outer",on = "course_id")

course.merge(reg,how = "left",on = "course_id")

# 1. find total revenue generated

total_revenue = int(reg.merge(course,how = "inner",on="course_id")["price"].sum())
total_revenue

tem_1 = pd.concat([nov,dec],keys = ["nov","dec"]).reset_index()
tem_1

# 2. find month by month revenue
tem_1.merge(course,how = "inner",on = "course_id").groupby("level_0")["price"].sum()

# Print the registration table

student

reg

course

regis = reg.merge(student,on = "student_id").merge(course,on = "course_id")
regis

#Print the registration table

reg.merge(student,on = "student_id").merge(course,on = "course_id")[["name","course_name","price"]]

#Plot bar chart for revenue/course
reg.merge(course,how = "inner",on="course_id")

reg.merge(course,how = "inner",on="course_id").groupby("course_name")["price"].sum()

reg.merge(course,how = "inner",on="course_id").groupby("course_name")["price"].sum().plot(kind="bar")

## 5. find students who enrolled in both the months

common_student = np.intersect1d(nov["student_id"],dec["student_id"])
common_student

student[student["student_id"].isin(common_student)]

# 6. find course that got no enrollment

course_id_list = np.setdiff1d(course["course_id"],regis["course_id"])
course_id_list

course[course["course_id"].isin(course_id_list)]

## 7. find students who did not enroll into any courses
student_id_list = np.setdiff1d(student["student_id"],regis["student_id"])
student_id_list

course[student["student_id"].isin(student_id_list)]

course[student["student_id"].isin(student_id_list)].shape[0]

student

# 8. Print student name -- partner name for all enrolled students
# that is self join

students = student.merge(student,how = "inner",left_on="partner",right_on="student_id")
students

students = student.merge(student,how = "inner",left_on="partner",right_on="student_id")[["name_x","name_y"]]

students = student.merge(student,how = "inner",left_on="partner",right_on="student_id")[["name_x","name_y"]].rename({"name_x":"Student_Name",
         "name_y":"Partner_name"},axis=1)
students

# 9. find top 3 students who did most number enrollments
regis

# # 9. find top 3 students who did most number enrollments

regis.groupby(["student_id","name"])["name"].count().sort_values(ascending=False).head(3)

# 10. find top 3 students who spent most amount of money on courses

 regis

regis.groupby(["student_id","name"])["price"].sum().sort_values(ascending=False)

regis.groupby(["student_id","name"])["price"].sum().sort_values(ascending=False).head(3)

## Alternate syntax for merge - pd.merge

pd.merge(student,regis,how = "inner",on = "student_id")

delivery = pd.read_csv("/content/deliveries (1).csv")

matches = pd.read_csv("/content/matches (6).csv")

delivery

matches

temp_2 = delivery.merge(matches,left_on="match_id",right_on="id")
temp_2

temp_2.columns

# find top 3 stadiums with highest sixes/match ratio
six = temp_2[temp_2['batsman_runs']==6]
num_six = six.groupby('venue')['batsman_runs'].count().sort_values(ascending=False)
num_six

num_matches = matches["venue"].value_counts()
num_matches

match_ratio = num_six/num_matches
match_ratio.sort_values(ascending=False)

match_ratio.sort_values(ascending=False).head(3).rename("match_ratio")

# find orange cap holder of all the seasons
temp_2

temp_2.columns

# find orange cap holder of all the seasons
Batsman_run = temp_2.groupby(['season','batsman'])['batsman_runs'].sum()
Batsman_run.sort_values(ascending=False)

Batsman_run.reset_index().sort_values("batsman_runs",ascending=False)

Batsman_run.reset_index().sort_values("batsman_runs",ascending=False).drop_duplicates(subset=["season"]).sort_values("season")