# -*- coding: utf-8 -*-
"""MultiIndex Series and DataFrames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYVQwkJId1MPidioDY-eTjJPx6heA8Il
"""

import pandas as pd
import numpy as np
import seaborn as sns

# how to create multilevel index
index_var = [("maths",2019),("maths",2020),("maths",2021),("science",2019),("science",2020),("science",2021)]
index_var

multiindex = pd.MultiIndex.from_tuples(index_var)

print(multiindex)

multiindex[0]

multiindex[0][1]

multiindex[1]

int(multiindex[1][1])

multiindex[1][0]

multiindex2 = pd.MultiIndex.from_product([["maths","English"],[2019,2020,2021]])

multiindex2

# create series with multiindex

s = pd.Series([1,2,3,4,5,6],index=multiindex)
s

int(s[("maths",2021)])

s["maths"]

# unstacck use Multiindex convert into dataframe

temp = s.unstack()
temp

temp1 = temp.stack()   ## stacck use dataframeconvert into Multiindex
temp1

# multilevel dataframe

branch_df1 = pd.DataFrame(
    [[1,2],
    [2,3],
    [4,5],
    [6,7],
    [8,9],
    [9,10]],

    index  = multiindex,
    columns = ["Avg_package","Students"]
)

branch_df1

branch_df1.loc["maths"]

branch_df1.loc["science"]

branch_df1["Avg_package"]

# #MultiIndex Data Frame from columns perspective



branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0]
    ],
    index=[2019,2020,2021,2022],
    columns=pd.MultiIndex.from_product([["delhi","mumbai"],["Avg_pack","Students"]])
)

print(branch_df2)

branch_df2

int(branch_df2.loc[2019]["delhi"]["Avg_pack"])

int(branch_df2.loc[2020]["delhi"]["Students"])

int(branch_df2.loc[2020]["delhi"]["Avg_pack"])

np.array([[1,23,3],
          [3,5,7]])

d = np.array([
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0]
    ],)

d.ndim

branch_df3 = pd.DataFrame(
    [
        [1,2,8,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
    ],
    index = multiindex2,
    columns=pd.MultiIndex.from_product([["delhi","mumbai"],["Avg_pack","Students"]])
)

branch_df3

##Stacking  and #Unstacking
branch_df3.unstack()

branch_df3.unstack().unstack()

branch_df3.stack()

branch_df3

branch_df3.stack()

branch_df3.stack().unstack()

branch_df3.unstack()

branch_df3.unstack().stack()

branch_df3

branch_df3.stack()

branch_df3.unstack()

"""📊 Main Difference

Feature	 stack() /  unstack()

Operation	Columns → Index	/ Index → Columns

Result	MultiIndex Series /  DataFrame

Use	Data reshape /	Pivot type table
"""

branch_df3.unstack().stack()

branch_df3.unstack().stack().stack()

branch_df3.unstack().stack().stack().stack()

#Working with #multiIndex DataFrames

branch_df2

branch_df2.head()

branch_df2.tail()

branch_df2.shape

branch_df2.ndim

branch_df2.info()

branch_df2.isnull().sum()

branch_df2.duplicated()

# # Extracting Single row

branch_df3

branch_df3.loc[("maths",2021)]

branch_df3.loc[("maths",2020)]

branch_df3

branch_df3.iloc[0:3:2]

branch_df3

## Extracting Cols
branch_df3["delhi"]

branch_df3["delhi"]["Students"]

int(branch_df3["delhi"]["Students"][5])

branch_df3

branch_df3.iloc[[0,4],[1,3]]  # that is fency indexing also

# sorting index
branch_df3.sort_index(ascending=False)

branch_df3.sort_index(ascending=True)

branch_df3.sort_index(ascending=[False,True])

branch_df3.sort_index(ascending=[True,True])

branch_df3.sort_index(ascending=[True,False])

branch_df3.sort_index(level=1 ,ascending=[False])

branch_df3.sort_index(level=0 ,ascending=[True])

branch_df3

# transpose

branch_df3.transpose()

##swaplevel
branch_df3

branch_df3.swaplevel()

branch_df3.swaplevel(axis=1)









