# -*- coding: utf-8 -*-
"""numpy .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_L9QwALhGjfjJmpyQiVvofbKBOqWjlhO
"""

import numpy as np
import pandas as pd

a1 = np.array([[[1,2,3],[6,9,0],[6,78,9]],[[4,5,6],[7,9,0],[8,9,7]],[[5,6,7,],[8,9,7],[9,6,4]]])
a1

a1[2][2][2]

a1.shape

a = np.array([12,3,7])
a

a1.ndim

a1[:, :, ::1][:3][1:2]

int(a1[2][2][2])

a1[1,0,[0,2]]

np.array([[1,2,3],[6,8,9]]).shape

np.array([[[5,7,8],[9,7,5]]])

np.array([[[5,7,8],[9,7,5]],[[6,8,9],[8,9,4]],[[8,9,4],[89,90,8]]])

A1 = np.arange(1,11)
A1

A1.reshape(2,5).ndim

np.arange(1,49).reshape(3,4,4)

np.arange(1,37).reshape(3,4,3).ndim

np.array([1,2,3]).ndim

np.array([[1,2,3],[8,9,0]])

np.array([[1,2,3],[8,9,0]]).ndim

np.array([[[3,6,8],[8,9,0]],[[7,8,5],[9,7,4]]])

np.array([[[3,6,8],[8,9,0]],[[7,8,5],[9,7,4]],[[8,6,4],[1,7,4]]])

np.array([[[3,6,8],[8,9,0]],[[7,8,5],[9,7,4]],[[8,6,4],[1,7,4]]]).ndim

np.array([[[3,6,8],[8,9,0]],[[7,8,5],[9,7,4]],[[8,6,4],[1,7,4]]]).shape

np.ones((3,6)).astype(np.int32)

np.zeros((3,6))

np.random.random((5,6))*2

np.linspace(0,10,5).astype(np.int32)*2

a2 = np.arange(1,49).reshape(3,4,4)
a2

a2 > 12 # relational operator

d1 = np.arange(1,43).reshape(3,7,2)
d1

d2 = np.array([[[1,2,4],[4,6,7]],[[4,6,7],[5,6,7]]])
d2

np.random.randint((2,3))

np.random.randint(1,10)

a = np.random.random((3,3))
a

a = np.round(a*100)
a

a = np.random.random((3,3))
a = np.round(a*100)
a

np.max(a)

np.min(a)

np.sum(a)

np.prod(a)

np.max(a,axis = 1)

np.max(a,axis = 0)

np.sum(a,axis = 1)

np.sum(a,axis = 0)

np.prod(a,axis = 0)

np.prod(a,axis = 1)

np.mean(a)

np.mean(a,axis=1)

np.mean(a,axis=0)

np.mod(a,3)

np.mod(a,5)

d2 = np.arange(12).reshape(3,4)
d3 = np.arange(12).reshape(4,3)

np.dot(d2,d3)

np.dot(d2,d3).ndim

np.dot(d2,d3).shape

np.round(np.mean(a))

np.floor(np.mean(a))

np.ceil(np.mean(a))

np.round(np.mean(a)*100)

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

a2

a3

a3[1,1,1]

a3[1,1,0]

a4 = np.arange(1,49).reshape(3,4,4)
a4

a4[2,2,2:5]

a4[2,0:4,0:5]

a5 = np.arange(1,13).reshape(3,4)
a5

a5[2,:]

a5[:,1]

a5

a5[1:3,1:3]

a5[1:3,1:4]

a5[0:2,2:4]

a5[1:3,3:4]

a6 = np.arange(1,49).reshape(3,4,4)
a6

a6[2,1:3,1:3]

a6[2,2:3,1:]

a6[1:2,1:3,1:4]

a6

a6[2,1::2,:]

a6[2,1::2,1::2]

a6[2,0::3,1::2]

a6

a6[1,:,:]

a6[1:3,:,:]

a6[0:3,:,:]

a6[0:2,:,:]

a6[1]

a6[1:3]

a6[0:3]

a6[0]

a6[2]

a6

a6[0:3,1:2,:]

a6[1]

a6[1,:,1:2]

a6[1,:,1:3]

a6[1,:,1]

a6[1,:,2]

a6

a6[::2,0,0::3]

a6[:,0,0::3]

a6

a6[::2,1:,:]

a6[::2,1:3,1:]

a6[::2,1:3,1:4]

a6

a6[1:,]

a6[1:,0::2]

a6[1:,0::2,:]

a6[1:,0::2,1:]

a6[1:,0::2,1:3]

a6

for i in a6:
  print(i)

for i in np.nditer(a6):
  print(i)

a6

np.transpose(a6)

a2

np.transpose(a2)

np.transpose(a2)

a2.T

a6

a6.ravel()

a2

a2.ravel()

np.arange(1,15).reshape(7,2)

np.arange(1,15).reshape(7,2).T

np.arange(1,15).reshape(7,2).ravel()

np.arange(1,13).reshape(4,3).ravel()

np.arange(1,13).reshape(4,3).T

a7 = np.arange(1,10).reshape(3,3)
a8 = np.arange(10,19).reshape(3,3)

np.vstack((a7,a8))

np.hstack((a7,a8))

a7 = np.arange(1,10).reshape(3,3)
a8 = np.arange(10,19).reshape(3,3)
a9 = np.arange(19,28).reshape(3,3)

g = np.vstack((a7,a8,a9))
g

np.hstack((a7,a8,a9))

import numpy as np

df1 = np.array([[[1,2,3,5],[2,3,45,6]],
                [[2,3,4,6],[8,9,5,6]]])

print(df1)

df1[1,0:,1:3]

import time

a11 = [i for i in range(10000000)]
b12 = [i for i in range(10000000,20000000)]

c = []
start = time.time()
for i in range(len(a)):
  c.append(a11[i] + b12[i])
print(time.time()-start)

import numpy as np
import time

a13 = np.arange(10000000)
b13 = np.arange(10000000,20000000)

start = time.time()

c13 = a13 + b13
print(c13)

print("Time taken:", time.time() - start)

1.1253936290740967/0.016484737396240234

# memory store

a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

b = np.arange(10000000)
sys.getsizeof(b)

b = np.arange(10000000,dtype = np.int32)
sys.getsizeof(b)

b = np.arange(10000000,dtype = np.int16)
sys.getsizeof(b)

b = np.arange(10000000,dtype = np.int8)
sys.getsizeof(b)

c = [i for i in range(100000)]
sys.getsizeof(c)

d = np.arange(100000)
sys.getsizeof(d)

d = np.arange(100000,dtype = np.int32)
sys.getsizeof(d)

# fancy indexing

a = np.arange(24).reshape(6,4)
a

a[[0,2,3,5]]

a[[1,5]]

# boolean indexing

a = np.random.randint(1,100,24).reshape(6,4)
a

# find all number greater than 50
a>50

a[a>50]

a == 56

a[a == 56]

# find out even number

a%2==0

a[a%2==0]

## find out odd number
a%2 !=0

a[a%2 !=0]

# find all number greater than 50 and even number

(a>50) & (a%2==0)

a[(a>50) & (a%2==0)]

# find all number greater than 50 and odd number

(a>40) & (a%2!=0)

a[(a>40) & (a%2!=0)]

# find all number not divisible by 7

a%7 !=0

a[a%7 !=0]

# find all number divisible by 7
a%7 == 0

a[a%7 == 0]

b=a
b

# find all number divisible by 5
a%5==0

a[a%5==0]

# find all number not divisible by 5
a[~(a%5==0)]  # not operator

import numpy as np

def log_loss(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    loss = -(y_true*np.log(y_pred) + (1-y_true)*np.log(1-y_pred))

    return np.mean(loss)

log_loss(1,.9)

#

import matplotlib.pyplot as plt

#x = y
x= np.linspace(-10,10,100)
y = x

plt.plot(x,y)

#

import matplotlib.pyplot as plt

#y = x**2
x= np.linspace(-10,10,100)
y = x**2

plt.plot(x,y)

# y = sin(x)

x = np.linspace(-10,10,100)
y = np.sin(x)
plt.plot(x,y)

# y = cos(x)

x = np.linspace(-10,10,100)
y = np.cos(x)
plt.plot(x,y)

# y = tan(x)

x = np.linspace(-10,10,100)
y = np.tan(x)
plt.plot(x,y)

# np.sort

a = np.random.randint(1,100,15)
a

np.sort(a)

b = np.random.randint(1,100,15).reshape(3,5)
b

np.sort(b)

np.sort(b,axis=0)

#Descending Order
np.sort(b)[::-1]

np.sort(a)[::-1]

np.append(b,299)

d2 = np.arange(12).reshape(3,4)
d3 = np.arange(12).reshape(3,4)

np.concatenate((d2,d3),axis=1)

d2 = np.arange(12).reshape(3,4)
d3 = np.arange(18).reshape(3,6)

d1 = np.concatenate((d2,d3),axis=1)
d1

np.unique(d1)

d1

np.sort(d1,axis=0)

d2 = np.arange(1,40)
d2

np.where(d2%2==0,"Even","odd")

np.where(d2%2==0,"Even",
         np.where(d2%2 !=0,"Even","odd"))

d2

np.where(d2>5,"Minor",np.where(d2>18,"Adult","old"))

a

np.where(a>50,0,a)

np.where(a>50)

np.argmax(a)

np.argmin(a)

g

np.argmin(g,axis = 0)

np.argmax(g,axis=1)

a

np.cumsum(a)

np.cumprod(a)

g

np.cumsum(g,axis=1)

np.cumsum(g,axis=0)

np.cumprod(g,axis=1)

np.percentile(a,100)

np.percentile(a,97)

df1 = pd.read_csv("/content/credit_card.csv",sep="")
df1 = df1.squeeze()

print(type(df1))

df1.describe()

df1 = pd.read_csv("/content/credit_card.csv")
series = df1.squeeze()

print(type(series))

import pandas as pd

df1 = pd.read_csv("/content/credit_card.csv",index_col="Client_Num")
df1 = df1.squeeze()

print(type(df1))

df1.head()

df = df1["Card_Category"]
type(df.squeeze())