# -*- coding: utf-8 -*-
"""pivot_tables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKykteT6RFXkK3TfhR13bZjLE0GfDqv0
"""

import pandas as pd
import numpy as np
import seaborn as sns

df1 = sns.load_dataset("tips")
df1.head()

# create pivota table

pivot_table = df1.pivot_table(index = "sex",columns = "smoker",values = "total_bill")
pivot_table

# aggfun

pivot_table1 = df1.pivot_table(index = "sex",columns = "smoker",values = "total_bill",aggfunc="sum")
pivot_table1

pivot_table2 = df1.pivot_table(index = "sex",columns = "smoker",values = "total_bill",aggfunc="count")
pivot_table2

pivot_table3 = df1.pivot_table(index = "sex",columns = "smoker",values = "total_bill",aggfunc=["mean","sum","count"])
pivot_table3

pivot_table4 = df1.pivot_table(index = "sex",columns = "smoker",values = "total_bill",aggfunc=["mean","sum","count","std"])
pivot_table4

pivot_table5 = df1.pivot_table(index = "sex",columns = "smoker",values = ["total_bill","tip","size"])
pivot_table5

pivot_table6 = df1.pivot_table(index = ["sex","smoker"],columns = ["day","time"],values = "total_bill")
pivot_table6

pivot_table7 = df1.pivot_table(index = ["sex","smoker"],columns = ["day","time"],values = ["total_bill","tip","size"])
pivot_table7

pivot_table8 = df1.pivot_table(index = ["sex","smoker"],columns = ["day","time"],values = ["total_bill","tip","size"],aggfunc={"total_bill":"sum","tip":"max","size":"mean"})
pivot_table8

pivot_table9 = df1.pivot_table(index = ["sex","smoker"],columns = ["day","time"],values = ["total_bill","tip","size"],aggfunc={"total_bill":"sum","tip":"min","size":"mean"})
pivot_table9

# mergin

pivot_table6 = df1.pivot_table(index = ["sex","smoker"],columns = ["day","time"],values = "total_bill",margins=True)
pivot_table6

pivot_table9 = df1.pivot_table(index = ["sex","smoker"],columns = ["day","time"],values = ["total_bill","tip","size"],aggfunc={"total_bill":"sum","tip":"min","size":"mean"},margins=True)
pivot_table9

